In [7]:
import numpy as np, pandas as pd

In [8]:
import tensorflow as tf

In [9]:
pathToFile = 'shakespeare.txt'

In [10]:
text = open(pathToFile,'r').read()

In [11]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [12]:
vocab = sorted(set(text))

In [13]:
len(vocab)

84

In [14]:
charToIndex = {char:ind for ind,char in enumerate(vocab)}

In [15]:
charToIndex

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [16]:
charToIndex['H']

33

In [17]:
indexToChar = np.array(vocab)

In [18]:
indexToChar[33]

'H'

In [19]:
encodedText = np.array([charToIndex[c] for c in text])

In [20]:
encodedText

array([ 0,  1,  1, ..., 30, 39, 29])

In [21]:
encodedText.shape

(5445609,)

In [22]:
sample = text[500:1000]

In [23]:
print(sample)

d buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su


In [24]:
encodedText[500:1000]

array([59,  1, 57, 76, 73, 64, 60, 74, 75,  1, 75, 63, 80,  1, 58, 70, 69,
       75, 60, 69, 75,  8,  0,  1,  1, 26, 69, 59,  1, 75, 60, 69, 59, 60,
       73,  1, 58, 63, 76, 73, 67,  1, 68, 56, 66,  5, 74, 75,  1, 78, 56,
       74, 75, 60,  1, 64, 69,  1, 69, 64, 62, 62, 56, 73, 59, 64, 69, 62,
       21,  0,  1,  1,  1,  1, 41, 64, 75, 80,  1, 75, 63, 60,  1, 78, 70,
       73, 67, 59,  8,  1, 70, 73,  1, 60, 67, 74, 60,  1, 75, 63, 64, 74,
        1, 62, 67, 76, 75, 75, 70, 69,  1, 57, 60,  8,  0,  1,  1,  1,  1,
       45, 70,  1, 60, 56, 75,  1, 75, 63, 60,  1, 78, 70, 73, 67, 59,  5,
       74,  1, 59, 76, 60,  8,  1, 57, 80,  1, 75, 63, 60,  1, 62, 73, 56,
       77, 60,  1, 56, 69, 59,  1, 75, 63, 60, 60, 10,  0,  0,  0,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, 13,  0,  1,  1, 48, 63, 60, 69,  1, 61, 70, 73, 75, 80,  1,
       78, 64, 69, 75, 60, 73, 74,  1, 74, 63, 56, 67, 67,  1, 57, 60, 74,
       64, 60, 62, 60,  1

In [25]:
sequenceLength = 120
totalSequence = len(text) // (sequenceLength+1)

In [26]:
totalSequence

45005

In [27]:
charDataset = tf.data.Dataset.from_tensor_slices(encodedText)

In [28]:
type(charDataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [29]:
sequences = charDataset.batch(sequenceLength+1, drop_remainder=True)

In [30]:
def createSequenceTarget(seq):
  input_text = seq[:-1]
  target_text = seq[1:]
  return input_text,target_text

In [31]:
dataset = sequences.map(createSequenceTarget)

In [32]:
# 1st batch : 
for inputText,targetText in dataset.take(1):
    print(inputText.numpy())
    print("".join(indexToChar[inputText.numpy()]))
    print("\n")
    print(targetText.numpy())
    print("".join(indexToChar[targetText.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [33]:
batchSize = 128

In [34]:
bufferSize = 10000
dataset = dataset.shuffle(bufferSize).batch(batchSize,drop_remainder=True)

In [35]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [36]:
len(vocab)

84

In [37]:
vocabSize = len(vocab)
embedDims = 64
rnnNeurons = 1026

In [38]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [39]:
def sparseCatLoss(y_true, y_pred):
  return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [40]:
from tensorflow.keras.models import Sequential

In [41]:
from tensorflow.keras.layers import Embedding,GRU,Dense

In [42]:
def createModel(_vocabSize, _embedDims, _rnnNeurons, _batchSize):
  model = Sequential([
          Embedding(_vocabSize, _embedDims, batch_input_shape = [_batchSize,None]),
          GRU(_rnnNeurons,return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'),
          Dense(_vocabSize)
  ])
  model.compile('adam', loss = sparse_categorical_crossentropy)
  return model

In [43]:
 model = createModel ( _vocabSize = vocabSize,
                       _embedDims = embedDims,
                       _rnnNeurons = rnnNeurons,
                       _batchSize = batchSize)

In [44]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1026)         3361176   
_________________________________________________________________
dense (Dense)                (128, None, 84)           86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [45]:
for inputExampleBatch,targetExampleBatch in dataset.take(1):
  exampleBatchPredictions = model(inputExampleBatch)

In [46]:
exampleBatchPredictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[-0.00405877, -0.0031926 ,  0.00437547, ...,  0.00382049,
         0.00147452,  0.00215603],
       [-0.00063046, -0.00200269, -0.00774149, ...,  0.00752806,
         0.00308234,  0.00017884],
       [ 0.00206812,  0.00154192,  0.00159745, ...,  0.00374575,
         0.00333671,  0.00506078],
       ...,
       [ 0.00394621, -0.0051925 , -0.00805531, ...,  0.00716522,
        -0.00382652,  0.01063507],
       [ 0.00228172, -0.00146451,  0.00037656, ...,  0.00021519,
        -0.00010536,  0.00184603],
       [ 0.00329038,  0.00037758,  0.00341793, ..., -0.00281705,
         0.00124753, -0.00275264]], dtype=float32)>

In [47]:
sampleIndices = tf.random.categorical(exampleBatchPredictions[0], num_samples=1)

In [48]:
sampleIndices = tf.squeeze(sampleIndices, axis=-1).numpy()

In [49]:
indexToChar[sampleIndices]

array(['\n', 'b', 'B', 'q', 'R', ' ', 'O', 'k', '0', '3', 'c', 'T', 'n',
       'r', 'L', '3', '!', 'O', 'V', 'N', '`', 'E', 'o', 'k', 'M', 'h',
       ' ', 'U', 'L', 'b', 'w', 'e', 'l', 'd', 'i', 'S', 'g', 'N', 't',
       '!', '!', '3', 'D', "'", 'B', 'a', 'A', 'a', '"', 'G', '<', 'z',
       'y', 'A', '(', 'n', '5', 'y', 'j', '1', ',', 'r', 'l', 'b', 'e',
       ';', 'f', 'P', 'x', 'l', 'H', 'a', '-', 't', '1', 'i', 't', 'o',
       '1', 'p', 'Q', 'L', 'P', '"', '.', 'b', '"', 'm', 'a', '>', '<',
       '>', 'Y', 'k', '_', 'P', 'n', '?', '[', 'z', '6', ':', '9', 'S',
       'J', ';', '0', 'k', 'Q', 'W', '`', 'Q', 'w', 'z', ',', 'I', 'N',
       'R', '7', 'F'], dtype='<U1')

In [50]:
epochs = 30

In [51]:
model.fit(dataset, epochs = epochs)

Epoch 1/30
351/351 [==============================] - 92s 261ms/step - loss: 2.9564
Epoch 2/30
351/351 [==============================] - 91s 260ms/step - loss: 2.6725
Epoch 3/30
351/351 [==============================] - 91s 261ms/step - loss: 2.6058
Epoch 4/30
351/351 [==============================] - 91s 260ms/step - loss: 2.6553
Epoch 5/30
351/351 [==============================] - 91s 259ms/step - loss: 2.6121
Epoch 6/30
351/351 [==============================] - 92s 261ms/step - loss: 2.5465
Epoch 7/30
351/351 [==============================] - 91s 260ms/step - loss: 2.5274
Epoch 8/30
351/351 [==============================] - 91s 261ms/step - loss: 2.8277
Epoch 9/30
351/351 [==============================] - 92s 262ms/step - loss: 2.7663
Epoch 10/30
351/351 [==============================] - 92s 262ms/step - loss: 2.7647
Epoch 11/30
351/351 [==============================] - 92s 261ms/step - loss: 2.6453
Epoch 12/30
351/351 [==============================] - 92s 262ms/step - lo

In [61]:
from tensorflow.keras.models import load_model

In [62]:
model.save('shakespeare_gen.h5')

In [67]:
model = createModel(_vocabSize=vocabSize,
                    _embedDims=embedDims,
                    _rnnNeurons=rnnNeurons,
                    _batchSize=1)
model.load_weights('shakespeare_gen.h5')
model.build(tf.TensorShape([1,None]))

In [68]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_3 (GRU)                  (1, None, 1026)           3361176   
_________________________________________________________________
dense_3 (Dense)              (1, None, 84)             86268     
Total params: 3,452,820
Trainable params: 3,452,820
Non-trainable params: 0
_________________________________________________________________


In [72]:
def generateText(_model, _startSeed, _genSize=500, _temp=1.0):
  num_to_generate = _genSize
  input_eval = [charToIndex[s] for s in _startSeed]
  input_eval = tf.expand_dims(input_eval,0)
  generatedText = []
  temperature = _temp
  _model.reset_states()
  
  for i in range(num_to_generate):
    predictions = _model(input_eval)
    predictions = tf.squeeze(predictions,0)
    predictions = predictions/temperature
    predicted_index = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
    input_eval = tf.expand_dims([predicted_index],0)
    generatedText.append(indexToChar[predicted_index])
  return (_startSeed+ "".join(generatedText))

In [73]:
print(generateText(_model=model,_startSeed="JULIET", _genSize=1000))

JULIETES] What, what? in cords, forsworn; lords, good win,
    You have shak'd first seen when he will be,
    And then I'll make thee friendly with the foot,
    As will return, and hear me speak it for your
    own, the very jests will greet away me good its with beats my fleer
    The ruin of the world, or gracious mirth,
    Hearing thee harmen's at ours that should be ready.
  PUBLIUS. All dispossesses, pronation;
    Bloody, shall quickly took upon her,
    here, by their other sumage is bear.                        SCARUS. Let us wreck down, and creep into the coward,
    As true in love, so fit my brother would
    With wit of your companion!  
  THERSITES. No, true, to save him with such mighty honesty than he:
    'Will't was committed?
  BEROWNE. I cannot tell; thou sects and honourable
    or anying soul upon him; no, I will; and so the gentleman of this head
    Stood in this brown friend, and what 'Welliurd name, a rabble came.
  VOLUMNILUS. 'Tis so;  peace, but be avoide

In [71]:
from google.colab import files
files.download("shakespeare_gen.h5")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>